import { useCallback, useEffect, useMemo, useState } from "react"

import { DatabasesQueryResponse } from "@notionhq/client/build/src/api-endpoints"
import { Button, Flex, Box } from "components/atoms"

import { notion } from "libraries/notion"
import Head from "next/head"
import Image from "next/image"

export type MusicProps = {
  database: DatabasesQueryResponse | null;
}

export default function Music({
  database
}:MusicProps) {
  
  const albumList = useMemo(()=>{ return database?.results }, [database]);

  useEffect(()=>{
    console.log(albumList)
  }, [albumList])
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex>

        <Flex>
          {albumList?.map((eachAlbum, eachIndex)=>{
            const src = eachAlbum.properties["Cover URI"] ? eachAlbum.properties["Cover URI"]["url"] : "" || "";
            return(
              <Box key={`album-${eachAlbum.id}`}>
                {src &&
                  <Image width={"300px"} height={"300px"} alt={`album cover of ${eachAlbum.properties["Name"]}`} src={src}/>
                }
              </Box>
          )})}
        </Flex>
        
      </Flex>
    </>
    
  )
}

export async function getServerSideProps() {
  
  try {
    const database = await notion.databases.query({ database_id: process.env.NOTION_MUSIC_DB_ID || "" });
    return { props: { database } }
  }
  catch {
    return { props: { database: null } }
  }
}


