import { useCallback, useEffect, useMemo, useState } from "react"

import { DatabasesQueryResponse } from "@notionhq/client/build/src/api-endpoints"
import { Button, Flex, Box } from "components/atoms"

import { notion } from "libraries/notion"
import Head from "next/head"
import Image from "next/image"
import { Page } from "@notionhq/client/build/src/api-types"
import { MusicAlbumPropertyValueMap } from "libraries/notion/types"

export type MusicProps = {
  database: DatabasesQueryResponse | null;
  notionFileUrlPrefix?: string;
}

export type MusicAlbum = Page & {
  properties: MusicAlbumPropertyValueMap; // PropertyValueMap
}

export default function Music({
  database,
  notionFileUrlPrefix
}:MusicProps) {
  
  const albumList: MusicAlbum[] = useMemo(()=>{ return database?.results || [] }, [database]);

  useEffect(()=>{
    console.log(albumList)
  }, [albumList])
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex>

        <Flex>
          {albumList?.map((item, index)=>{

            const name = item.properties.Name?.title[0]
            const key = item.properties.Key?.rich_text[0]?.plain_text

            const src = key ? `${notionFileUrlPrefix}/${key}.jpg` : undefined;
            
            return(
              <Box key={`album-${item.id}`}>
                {src &&
                  <Image width={"300px"} height={"300px"} alt={`album cover of ${name}`} src={src}/>
                }
              </Box>
            )
          })}
        </Flex>
        
      </Flex>
    </>
    
  )
}

export async function getServerSideProps() {
  
  try {
    const database = await notion.databases.query({ database_id: process.env.NOTION_MUSIC_DB_ID || "" });
    return { props: { 
      database,
      notionFileUrlPrefix: process.env.NOTION_FILE_URL_PREFIX,
    } }
  }
  catch {
    return { props: { 
      database: null, 
      notionFileUrlPrefix: process.env.NOTION_FILE_URL_PREFIX } }
  }
}


